### ISSUE TITLE
Creating a lightweight version of gdal dependencies

### ISSUE THREAD

**Issue by RenaudLN** [conda-forge/gdal-feedstock#722]
### Comment:

Currently the `libgdal` feedstock includes a large number of dependencies that are not strictly required to use GDAL (e.g. poppler, postgres, ...). This bloats image sizes everytime we want to install a GDAL-related package like `geopandas`.

Would it be possible to create a lightweight version of the feedstock?

Maybe something like

```yaml
  - name: libgdal-lite
    script: install_lib.sh  # [unix], probably needs to be updated?
    script: install_lib.bat  # [win], probably needs to be updated?
    build:
      run_exports:
        # no idea, going with minor pin
        - {{ pin_subpackage('libgdal', max_pin='x.x') }}
    requirements:
      build:
        - cmake
        # ranlib used at install time
        - {{ compiler('c') }}
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
        - make  # [unix]
        - ninja  # [win]
        - sysroot_linux-64 2.17  # [linux64]
      host:
        - blosc
        - geos
        - icu
        - json-c  # [not win]
        - libcurl
        - libdeflate
        - libiconv
        - libkml
        - libnetcdf
        - libpng
        - libpq
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libwebp-base
        - libxml2
        - lz4-c
        - proj
        - zlib
        - zstd
      run:
        - json-c  # [not win]
        - libpq
        - libspatialite
        - libuuid  # [linux]
        - libwebp-base
        - proj
        - zstd
    test:
      files:
        - test_data
        - run_test.bat  # probably needs to be updated?
        - run_test.sh  # probably needs to be updated?
    about:
      summary: The Geospatial Data Abstraction Library (GDAL)
      license: MIT
      license_file: LICENSE.TXT
```
